# Generated by Django 5.0.7 on 2024-08-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='layout',
            field=models.JSONField(default=dict),
        ),
    ]
