# Generated by Django 5.0.7 on 2024-08-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0188_devicetype_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='layout',
            field=models.JSONField(null=True),
        ),
    ]
